lessonsPerDay: 3 # Кол-во уроков в день
daysPerWeek: 5 # Кол-во учебных дней в неделе
populations_qty: 100 # Количество популяций
classesQty: 4 # Количество классов
lessons: # Список всех уроков и их количество в неделе
  Алгебра: 4
  Геометрия: 3
  Физика: 4
  Английский язык: 1
  Информакика: 3
