lessonsPerDay: 4 # Кол-во уроков в день
daysPerWeek: 6 # Кол-во учебных дней в неделе
populations_qty: 100 # Количество популяций
classesQty: 1 # Количество классов
lessons: # Список всех уроков и их количество в неделе
  Алгебра: 5
  Геометрия: 4
  Физика: 3
  Английский язык: 5
  Информатика: 4
  Русский Язык: 4
