lessonsPerDay: 5 # Кол-во уроков в день
daysPerWeek: 3 # Кол-во учебных дней в неделе
populations_qty: 100 # Количество популяций
classesQty: 2 # Количество классов
lessons: # Список всех уроков и их количество в неделе
  Алгебра: 4
  Русский Язык: 3
  Биология: 4
  Теория Познания: 1
  Английский язык: 3